name: Core
version: $version
description: $description

main: me.outspending.core.Core
api-version: $apiVersion

authors:
  - Outspending
  - Azuyamat

depend:
  - LuckPerms
  - FastAsyncWorldEdit # For Private Mines (Schematics)
